mas_config_name: "dev1-bas-system"
mas_config_chart: ibm-mas-bas-config
mas_config_scope: system
mas_workspace_id:
mas_application_id:
mas_config_kind: "bascfgs"
mas_config_api_version: "config.mas.ibm.com"

mas_instance_id: dev1
dro_api_token: <path:arn:aws:secretsmanager:us-east-2:435377327995:secret:demo/demo1/dro#dro_api_token>
dro_endpoint_url: ibm-data-reporter-redhat-marketplace.gitopsdemo2-6f1620198115433da1cac8216c06779b-0000.eu-gb.containers.appdomain.cloud
dro_contact:
  email: iotf@uk.ibm.com
  first_name: David
  last_name: Parker
dro_ca:
  crt: |
    -----BEGIN CERTIFICATE-----
    MIIF0TCCBLmgAwIBAgISAyLxZvDh0wHxwKPuItQ4hNKSMA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yNDAyMDgxNTA0MDdaFw0yNDA1MDgxNTA0MDZaMDcxNTAzBgNVBAMT
    LGdpdG9wc2RlbW8yLmV1LWdiLmNvbnRhaW5lcnMuYXBwZG9tYWluLmNsb3VkMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn8N+4X2i33M5LRksc42wLLSl
    DGOad+KOA3mUAVR/wYlk+Hknpixaol1EhPdHTMiZwEsrLmTxhJHiD4qZ/IfuxE0q
    OtvGOOnnFaGOrvaRQvdbfhKZpsGZYuKffWQMzjDOQ+8bOfWxk2lNH7DgZGLLLzns
    jlHxp5HJAhURt8undedczoFiv+9PeUFYOVnrp7IqYadkVVxlpcPALcoxTmbH4L2V
    fr1vWFQ97u/HxrN3i9AZ9peuMAFFLltzopwtlW8VtnF/h3cS4pX23d9RWe9JMuTt
    j0yqiRqnandV0MQ55DTgvdvoObOt1HdhTe/zkL+aeVBvqIWekdN0pYL2UQC6QQID
    AQABo4IC2jCCAtYwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRzxdSEy1KBwOkDOeU7
    6kNMt+KpsDAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEF
    BQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggr
    BgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzCB4wYDVR0RBIHbMIHYglQq
    LmdpdG9wc2RlbW8yLTZmMTYyMDE5ODExNTQzM2RhMWNhYzgyMTZjMDY3NzliLTAw
    MDAuZXUtZ2IuY29udGFpbmVycy5hcHBkb21haW4uY2xvdWSCUmdpdG9wc2RlbW8y
    LTZmMTYyMDE5ODExNTQzM2RhMWNhYzgyMTZjMDY3NzliLTAwMDAuZXUtZ2IuY29u
    dGFpbmVycy5hcHBkb21haW4uY2xvdWSCLGdpdG9wc2RlbW8yLmV1LWdiLmNvbnRh
    aW5lcnMuYXBwZG9tYWluLmNsb3VkMBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBAwYK
    KwYBBAHWeQIEAgSB9ASB8QDvAHYASLDja9qmRzQP5WoC+p0w6xxSActW3SyB2bu/
    qznYhHMAAAGNiXZJzwAABAMARzBFAiAjTT/vTuXfVWmHPZ2VgB+IOpQ4mTu1AEz6
    z2qHeNgemQIhANEtahBgIlPI8zm0HIvWDw5i5MGdfi3+P7iFFDJgVIihAHUAdv+I
    Pwq2+5VRwmHM9Ye6NLSkzbsp3GhCCp/mZ0xaOnQAAAGNiXZKJAAABAMARjBEAiA/
    KHP01z0mfFsMvz3uccaGuOHP/dk8uMhYHOieirPuSwIgVksCj4AVg4w7OFXOTKPD
    wSFvcTa8E6bIKU6Nni2kVgswDQYJKoZIhvcNAQELBQADggEBAEyURGsie/PBJbR5
    mXU6nO5YbBE+MtqMX2c54A2zFrUjzPfYhfXBiP8Wq1NgPnM7OqNlAKofWIdunfPU
    9L70VkpuTRiMt3pQQCNvpO2cpHXtYA9UmirHurmSOsOBvx/9N/Zj22GsuICvtpId
    AQCJb9ugRxHLkwuSng+0jRsOjbCx8kXnhIr8NHZ6d6mJYFwInI1lvpooLFFSRpW8
    UoR5O/kpTR0CPw193rCP3V+R/ocggGZexeAacltqfNV77pGDYJQhShAC4S7TgW5T
    wE1jxI/uPqFDoKPY8QFLVzUbbIpChRs3XkpHqGEy6C7Ph4sBqURr/THhf1eoZ4kH
    XD0CHnQ=
    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----
    MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
    WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
    R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
    sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
    NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
    Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
    /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
    Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
    FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
    AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
    Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
    gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
    PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
    ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
    CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
    lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
    avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
    yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
    yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
    hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
    HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
    MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
    nLRbwHOoq7hHwg==
    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----
    MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
    ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
    wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
    LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
    4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
    bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
    sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
    Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
    FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
    SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
    PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
    TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
    SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
    c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
    +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
    ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
    b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
    U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
    MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
    5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
    9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
    WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
    he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
    Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
    -----END CERTIFICATE-----
