CHNGPGS_THRESH: '40'
DFT_QUERYOPT: '5'
LOGBUFSZ: '1024'
LOCKLIST: 'AUTOMATIC'
MAXFILOP: '61440'
NUM_IOCLEANERS: 'AUTOMATIC'
NUM_IOSERVERS: 'AUTOMATIC'
STMTHEAP: '20000'
CUR_COMMIT: 'ON'
AUTO_REVAL: 'DEFERRED'
DEC_TO_CHAR_FMT: 'NEW'
DATABASE_MEMORY: 'AUTOMATIC'
PCKCACHESZ: 'AUTOMATIC'
DBHEAP: 'AUTOMATIC'
STAT_HEAP_SZ: 'AUTOMATIC'
SOFTMAX: '0'
CATALOGCACHE_SZ: '800'
LOCKTIMEOUT: '300'
LOGPRIMARY: '100'
LOGSECOND: '156'
LOGFILSIZ: '32768'
LOGARCHMETH1: 'DISK:/mnt/bludata0/db2/archive_log/'
MIRRORLOGPATH: '/mnt/backup/MIRRORLOGPATH'
STMT_CONC: 'LITERALS'
DDL_CONSTRAINT_DEF: 'YES'
TRACKMOD: 'YES'
AUTO_DEL_REC_OBJ: 'ON'
REC_HIS_RETENTN: '60'
NUM_DB_BACKUPS: '60'
DFT_TABLE_ORG: 'ROW'
AUTO_MAINT: 'ON'
AUTO_TBL_MAINT: 'ON'
AUTO_RUNSTATS: 'ON'
AUTO_REORG: 'OFF'
AUTO_DB_BACKUP: 'OFF'
WLM_ADMISSION_CTRL: 'NO'
SHEAPTHRES_SHR: 'automatic'
SORTHEAP: 'automatic'
AUTHN_CACHE_USERS: '100'
AUTHN_CACHE_DURATION: '10'
APPLHEAPSZ: '8192 AUTOMATIC'
