STRING_UNITS: 'CODEUNITS32'
DDL_CONSTRAINT_DEF: 'YES'
STMT_CONC: 'OFF'
LOGPRIMARY: '23'
LOGFILSIZ: '32768'
LOGSECOND: '12'
LOGBUFSZ: '8192'
LOCKTIMEOUT: '30'
CATALOGCACHE_SZ: '2048'
STMTHEAP: '60000 AUTOMATIC'
ENCRLIB: 'libdb2compr_encr.so'
